language: node_js
node_js: "10.22.0"

addons:
  chrome: stable

cache:
  directories:
    - "node_modules"

branches:
  only:
    - site-production

before_script:
  - npm install

script:
  - node server.js

jobs:
  include:
    - stage: test
      name: "Run Express Server"
      script: node server.js
